### ISSUE TITLE
WebOb changes

### ISSUE THREAD

**Issue by reedstrm** [pyupio/changelogs#110]
Looks like WebOb is doing something tricky: it moved most most of its  changelogs from CHANGES.txt to HISTORY.txt, but has a tempalte in docs/changestxt that includes both of those. Not sure if that auto-generates the webpage changelog, at https://docs.pylonsproject.org/projects/webob/en/stable/changes.html

I filed an issue w/ them, in case it was just an oversight during release: https://github.com/Pylons/webob/issues/357

**Comment by bertjwregeer** [comment]
It's not an oversight in WebOb. CHANGES.txt for the latest bug fix releases can be found in branches named `1.y-branch`.

We don't release bug fixes from master directly for point releases on major versions. This has always been the case.

The stable URL on Read the Docs points to the latest stable version, on the release of `1.9-branch` in the future it won't contain any information about the point releases made on `1.8-branch` due to the way we do our branching/documentation.

As was suggested on that issue by @mmerickel your best bet is to pull the sdist from PyPi since that will contain the latest information for that release, including all fixes.

**Comment by bertjwregeer** [comment]
https://docs.pylonsproject.org/projects/webob/en/stable/changes.html -> https://docs.pylonsproject.org/projects/webob/en/1.8-branch/changes.html

But that doesn't show any of the point release for WebOb 1.7.x, which you can find here:

https://docs.pylonsproject.org/projects/webob/en/1.7-branch/changes.html

Or, even better:

https://pypi.org/project/WebOb/1.8.1/ (Shows changelog of 1.8.0 -> 1.8.1)
https://pypi.org/project/WebOb/1.7.4/ (Shows changelog of 1.7.0 -> 1.7.4) 
https://pypi.org/project/WebOb/1.6.4/ (Shows changelog of 1.6.0 -> 1.6.4)

Further changes to any of those branches may be made. PyPi is your best bet for finding the changelogs.

**Comment by bertjwregeer** [comment]
https://pyup.io/changelogs/pyramid/ has the same issues btw and follows the same way of tracking changes.
