### ISSUE TITLE
Changelog: Django

### ISSUE THREAD

**Issue by tomhamiltonstubber** [pyupio/changelogs#25]
https://github.com/django/django/tree/master/docs/releases

**Comment by alexkiro** [comment]
I looked a bit into this, and there already is a custom parser for Django. There was a bug which is now fixed  and but not included in a new release where custom parser wouldn't work with different casing. (Refs. 21164655a0abb1c2055e13fa4bd3bb61beb239d8) 

@tomhamiltonstubber Likely you have `Django` in your requirements file instead of `django`? If so that will be fixed soon :)

**Comment by jayfk** [comment]
There was also a little issue yesterday on pyup.io fetching the new changelog. The initial fetch failed because the server ran into some kind of rate limiting. The first batch of Django updates was sent out without a changelog, updates later in the queue (~20 minutes) included it.

**Comment by tomhamiltonstubber** [comment]
@alexkiro That's correct, thanks.
